In [1]:
high_finesse_wavemeter

<qudi.hardware.wavemeter.high_finesse_wavemeter.HighFinesseWavemeter(0x225b51b7e90) at 0x00000225B9989D00>

In [2]:
buf = high_finesse_wavemeter.get_wavelength_buffer()

In [8]:
high_finesse_wavemeter.get_wavelength_buffer()

(array([0]), array([0]))

In [4]:
wavelogger_logic.update_data()

AttributeError: 'WavemeterLoggerLogic' object has no attribute 'start_toggled'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Users\yy3\Anaconda3\envs\squdi\lib\site-packages\rpyc\core\protocol.py", line 359, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\yy3\Anaconda3\envs\squdi\lib\site-packages\rpyc\core\protocol.py", line 837, in _handle_call
    return obj(*args, **dict(kwargs))
  File "C:\new_qudi\scudi\src\qudi\logic\wavemeter_logger_logic.py", line 158, in update_data
    if self.start_toggled:
AttributeError: 'WavemeterLoggerLogic' object has no attribute 'start_toggled'


In [5]:
wavelogger_logic.wavelengths.wavelength

array([[484.06657646],
       [484.06657646],
       [484.06657646],
       ...,
       [484.0665804 ],
       [484.06661413],
       [484.0665605 ]])

In [8]:
wavelogger_logic.wavelengths.time

array([[463.45136309],
       [463.56798625],
       [463.68462372],
       ...,
       [ 59.94601154],
       [ 60.12914824],
       [ 60.18838954]])

In [26]:
buf_rec = np.rec.array(np.array(buf), dtype=WAVELENGTH_DTYPE)